name: PowerShell Demo

on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get date
        shell: pwsh
        run: Get-Date

      - name: Current directory
        shell: pwsh
        run: Get-Location

      - name: List files
        shell: pwsh
        run: Get-ChildItem